### PR TITLE
Calendar

### PR DESCRIPTION
**Pull request by theVerySharpFlat**

### CODE REVIEW

**Comment by Ta180m** [comment]
Just wondering, what's the status of this PR right now?

**Comment by theVerySharpFlat** [comment]
It is coming. I have a calendar with text on the right that changes based on the date chosen by the calendar. I'm at robotics the next two days, so I won't be able to work on this. The first day I will probably restart working on this is monday at the latest.

**Comment by theVerySharpFlat** [comment]
I need to clean up the code a little and fix a small issue, but otherwise it is done.

**Comment by theVerySharpFlat** [comment]
Done. I also fixed two issues in other parts of the code with this commit:

1. Fixed the issue with people using class instead of className. I did this too until I saw the error in the developer console. Not sure what the difference is, but I fixed it.
2. Changed reactDOM.render to root.render to support react >= 18.0

**Review by Ta180m — APPROVED** [review]
Looks good, thanks for the PR!

**Comment by ADawesomeguy** [comment]
More like no thanks :(

**Pull request merged**
