### PR TITLE
Formated all files

### PR DESCRIPTION
**Pull request by notSam25**

### CODE REVIEW

**Review by Ta180m — CHANGES_REQUESTED** [review]
Only the jsx files?

**Comment by notSam25** [comment]
yes only jsx

**Review by Ta180m — CHANGES_REQUESTED** [review]
How about you optimize our images too

**Comment by notSam25** [comment]
wdym "optomize"

**Comment by Ta180m** [comment]
https://graphicdesign.stackexchange.com/questions/51593/how-to-optimize-images-to-improve-pagespeeds-webpage-loading-times

or convert our pngs to webps or something

**Review by notSam25 — COMMENTED** [review]
looks good

**Comment by notSam25** [comment]
Sure I can convert all our images to webp.

**Comment by Ta180m** [comment]
> looks good

self-review 👀

**Pull request merged**
