### PR TITLE
HTML/CSS rewrite

### LINKED ISSUE #61: Proposal: Rewrite in plain HTML + CSS
Now that we have a great website, does anyone want to try rewriting it in plain HTML + CSS with *zero* JavaScript? For a static website like this, I don't think we need any JavaScript, so it'd be a good exercise to try.

### PR DESCRIPTION
**Pull request by Ta180m**
Fixes #61.

There is a preview build available at https://laduecs.exozy.me/

### CODE REVIEW

**Comment by ADawesomeguy** [comment]
How did you even do this? Also is there a way to skip the scrolling text like in Pokémon?

**Comment by Ta180m** [comment]
@ADawesomeguy Just look at the source code, it's just a nice HTML file and a CSS file.

There's currently no way to skip the text but it shouldn't be too difficult to add if you know CSS.

**Comment by Ta180m** [comment]
`+184 −49,125`

Yay that's what I like to see!

“Perfection is achieved, not when there is nothing more to add, but when there is nothing left to take away.”
- Antoine de Saint-Exupéry

**Comment by Ta180m** [comment]
The only thing missing is the calendar but it wasn't complete on the old website anyways. It should be doable with some CSS but I think we can add that later.

**Comment by Ta180m** [comment]
Also, I'm not sure if this website works on all browsers so we should check that.

**Pull request merged**
